Repository khawajaazfar2000/Hacktoberfest2022-Repository-5, pull requests merged in 2022-10, with the labels that each got.

#1 do it
  Loop to print Number.cpp
  Loop to print Number.exe
Labels: hacktoberfest

#2 updated
  Loop to print Number.cpp
  Loop to print Number.exe
Labels: hacktoberfest, hacktoberfest-accepted

#3 Modified Readme File and also add python codes in structured manner
  Python Codes/duplicate.py
  Python Codes/factRecursion.py
  Python Codes/guess-game.py
  Python Codes/list_conversion.py
  Python Codes/login-demo.py
  Python Codes/lyrics.py
  Python Codes/min.py
  Python Codes/nestedF.py
  Python Codes/palindrome.py
  Python Codes/pattern-demo.py
  Python Codes/plaindrome.py
  Python Codes/powerRecur.py
  Python Codes/prog1.py
  Python Codes/prog2.py
  Python Codes/prog4.py
  Python Codes/sumprime.py
  Python Codes/table-demo.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#4 first commit
  Loop to print Number.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#5 List & Array ADDED
  List & array/DeleteAtBtw.cpp
  List & array/DeleteAtEnd.cpp
  List & array/DeleteAtStart.cpp
  List & array/InsertAtBetween.cpp
  List & array/InsertAtEnd.cpp
  List & array/InsertAtStart.cpp
  List & array/SearchOnce.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 Tower of Hanoi Code.cpp
  C++/TowerofHanoi.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 BFS_Traversal.cpp
  C++/BFS_Traversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#8 DFS_Adjacent_Matrix_Traversal.cpp
  C++/DFS_Adjacent_Matrix_Traversal.cpp
  C++/bubble_sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#10 Added mergesort.cpp
  C++/mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#12 Added two new python codes
  Python Codes/array-permutation.py
  Python Codes/good-pairs.py
  Python Codes/running-sum-array.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#13 Coding-Blocks-Code-Added (hacktoberfest22)
  C++/Coding-Blocks/.vscode/settings.json
  C++/Coding-Blocks/Array/binarySearch.cpp
  C++/Coding-Blocks/Array/binarySearch.exe
  C++/Coding-Blocks/Array/creatingSubarrays.cpp
  C++/Coding-Blocks/Array/creatingSubarrays.exe
  C++/Coding-Blocks/Array/largestSmallest.cpp
  C++/Coding-Blocks/Array/largestSmallest.exe
  C++/Coding-Blocks/Array/linearSearch.cpp
  C++/Coding-Blocks/Array/linearSearch.exe
  C++/Coding-Blocks/Array/selectionSort.cpp
  C++/Coding-Blocks/Array/selectionSort.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#14 added 2 more python codes
  Python Codes/minimum-sum-of-four-digts.py
  Python Codes/steps-to-reduce-number-to-zero.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#15 some more python codes
  Python Codes/kids-with-gratest-number-of-candies.py
  Python Codes/root-equals-sum-of-children.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22

#16 2 more python codes
  Python Codes/decode-XORed-list.py
  Python Codes/numbers-smaller-than-current-number.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest22
